; PUSH BASE
; PUSH EXP
; CALL CALCULAR_POTENCIA
; ADD SP, 8
; devuelve el resultado de la potencia en EAX

; RECURSIVO
CALCULAR_POTENCIA: PUSH BP
MOV BP, SP
PUSH EBX
MOV EAX, [BP + 8]; EAX = EXP
MOV EBX, [BP + 12]; EBX = BASE
CMP EAX, 0
JNZ RECURSIVO
MOV EAX,1
JMP FIN_CP
RECURSIVO: SUB EAX, 1
; LLAMADO RECURSIVO
PUSH EBX
PUSH EAX
CALL CALCULAR_POTENCIA
ADD SP, 8
MUL EAX, EBX ; EAX = BASE ^ (EXP - 1) * BASE
FIN_CP: POP EBX
POP BP
RET

; ITERATIVO
CALCULAR_POTENCIA: PUSH BP
MOV BP, SP
PUSH EBX
MOV EAX, 1; RESULTADO
MOV ECX, [BP + 12]; ECX = BASE
MOV EBX, [BP + 8]; EBX = EXP
ITERACION: CMP EBX, 0
JZ FIN_CP
MUL EAX, ECX
SUB EBX, 1
JMP ITERACION
FIN_CP: POP ECX
POP EBX
POP BP
RET
